// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRyBixb_jBW5RrUr-hYFBxykNVQyF6W5o',
    appId: '1:186794938284:web:2c4046590082488c83b409',
    messagingSenderId: '186794938284',
    projectId: 'language-creeper',
    authDomain: 'language-creeper.firebaseapp.com',
    databaseURL: 'https://language-creeper-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'language-creeper.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGGRqPfBrpnPMJL8zjz-_hXVe3wUJB90s',
    appId: '1:186794938284:android:ec5ea61c8aa4662b83b409',
    messagingSenderId: '186794938284',
    projectId: 'language-creeper',
    databaseURL: 'https://language-creeper-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'language-creeper.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByoOR3FYVlkQ-esBMQFUb8CpRZRBNkGpw',
    appId: '1:186794938284:ios:7c7c83f2f0c9a09183b409',
    messagingSenderId: '186794938284',
    projectId: 'language-creeper',
    databaseURL: 'https://language-creeper-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'language-creeper.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByoOR3FYVlkQ-esBMQFUb8CpRZRBNkGpw',
    appId: '1:186794938284:ios:7c7c83f2f0c9a09183b409',
    messagingSenderId: '186794938284',
    projectId: 'language-creeper',
    databaseURL: 'https://language-creeper-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'language-creeper.firebasestorage.app',
    iosBundleId: 'com.example.firstproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRyBixb_jBW5RrUr-hYFBxykNVQyF6W5o',
    appId: '1:186794938284:web:4afe0261db42175c83b409',
    messagingSenderId: '186794938284',
    projectId: 'language-creeper',
    authDomain: 'language-creeper.firebaseapp.com',
    databaseURL: 'https://language-creeper-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'language-creeper.firebasestorage.app',
  );

}